algoritmo "Nome do Programa"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : DATA_ATUAL/MES_ATUAL/ANO_ATUAL
var

    N1, N2: Inteiro
    media: Real

inicio

    escreva("Informe o 1º número: ")
    leia(N1)
    escreva("Informe o 2º número: ")
    leia(N2)
    media <- (N1 + N2) / 2
    escreva("A média entre ", N1, " e ", N2, " é: ", media)
fimalgoritmo

// Operadores aritméticos:
// +            Adição
// -            Subtração
// *            Multiplicação
// /            Divisão
// \            Divisão inteira (parte inteira da divisão)
// %            Módulo  (resto da divisão)
// ^            exponenciação

// Ordem de precedência:
// 1. () (Parenteses)
// 2. ^ (exponenciação)
// 3. * / (multiplicação / divisão)
// 4. + - (adição s subtração)