algoritmo "Combinações"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : DATA_ATUAL/MES_ATUAL/ANO_ATUAL
var
// https://www.youtube.com/watch?v=WJQz20i7CyI

    C1, C2: Inteiro

inicio

    Para C1 := 1 ate 3 faca
        Para C2 := 1 ate 3 faca

        escreval(C1, C2)
        FimPara
    FimPara


fimalgoritmo