algoritmo "Somador ENQUANTO"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : DATA_ATUAL/MES_ATUAL/ANO_ATUAL
var

    N, C, S: Inteiro

inicio
    C <- 1
    S <- 0

    Enquanto (C <= 5) faca
        escreva("Digite um valor: ")
        leia(N)
        S <- S + N
        C <- C + 1

    FimEnquanto
    escreval("A soma dos valores é ", S)

fimalgoritmo