algoritmo "Nome do Programa"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : DATA_ATUAL/MES_ATUAL/ANO_ATUAL
var

    anoAtual, anoDeNascimento, idade: Inteiro

inicio

    escreva("Em que ano estamos? ")
    leia(anoAtual)
    escreva("Em que ano você nasceu? ")
    leia(anoDeNascimento)

    idade <- anoAtual - AnoDeNascimento
    escreva("Voc6e tem ", idade, " anos de idade.")

fimalgoritmo