algoritmo "Valores Pares"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : DATA_ATUAL/MES_ATUAL/ANO_ATUAL
var

    Cont, Valor: Inteiro

inicio

    escreva("Digite um valor: ")
    leia(Valor)
    escreval("")
    Se(Valor % 2 = 1) entao
        Valor <- Valor - 1
    FimSe
    Para Cont <- valor ate 0 passo -2 faca
        escreval(Cont)
    FimPara

fimalgoritmo