algoritmo "Nome do Programa"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : DATA_ATUAL/MES_ATUAL/ANO_ATUAL
var

    valor, taxa: Real

inicio

    escreva("Qual o preço do produto? U$ ")
    leia(valor)

    taxa <- (valor * 60) / 100
    escreva("Você precisa pagar U$ ", taxa:5,2, " de impostos.")


fimalgoritmo