algoritmo "Nome do Programa"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : DATA_ATUAL/MES_ATUAL/ANO_ATUAL
var

    A, B, C: Inteiro

inicio

    A <- 2
    B <- 3
    C <- 5

    escreval("01. ", A > B)
    escreval(A = B)
    escreval(A != C)
    escreval(A > 2)
    escreval(A >= 2)

    escreval("---")

    escreval(C = A + B)
    escreval(C >= B ^ A)
    escreval(A = "R")

    escreval("---")

    escreval(B <= C % 2)
    escreval(1 = C % 2)

    escreval("---")

    escreval("11. ", verdadeiro E falso)
    escreval("12. ", (A = B) OU (C > A))


fimalgoritmo

// Operadores Relacionais

// >
// <
// >=
// <=       menor ou igual
// =       Igual a
// !=       Diferente de

// Operadores lógicos

// E
// OU
// NÃO