algoritmo "Nome do Programa"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : DATA_ATUAL/MES_ATUAL/ANO_ATUAL
var

    reais, dollar: Real

inicio

    escreva("Quantos reais você tem? R$")
    leia(reais)

    dollar <- reais / 5.5
    escreva("Você tem ", dollar, " dólares.")

fimalgoritmo