algoritmo "Nome do Programa"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : DATA_ATUAL/MES_ATUAL/ANO_ATUAL
var

    angulo, S: Real

inicio

    escreva("Informe um ângulo: ")
    leia(angulo)
    S <- Sen(GraupRad(angulo))
    escreval("O seno do ângulo ", angulo, "º é ", S)
fimalgoritmo
