algoritmo "Nome do Programa"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : DATA_ATUAL/MES_ATUAL/ANO_ATUAL
var

    A, B, C: Inteiro
    D, EE, F, G: Real
 

inicio

    A <- Abs(-50)
    escreval(A)

    B <- Exp(9,5)
    escreval(B)

    C <- RaizQ(81)
    escreval(C)

    D <- RaizQ(90)
    escreval(D)

    EE <- Int(RaizQ(90))
    escreval(EE)

    F <- GraupRad(90)
    escreval("A conversão de 90º para Radianos é: ", F)

    G <- Sen(GraupRad(90))
    escreval("O seno de 90º é: ", G)

fimalgoritmo