algoritmo "Conte até dez"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Estruturas de Repetição 01
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 2025-06-25
var

    contador: Inteiro

inicio

    contador <- 0

    Enquanto (contador <= 10) faca
        escreval(contador)
       //  contador <- contador + 1
    FimEnquanto

    escreval(contador)

fimalgoritmo

// Esse programa fica em loop infinito.