algoritmo "Conte de dez a zero"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Estruturas de Repetição 01
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 2025-06-25
var

    contador: Inteiro

inicio

    contador <- 10

    Enquanto (contador >= 0) faca
        escreval(contador)
        contador <- contador - 1

    FimEnquanto

    escreval("\nO valor final do contador é ", contador, ", mas esse valor não é exibido na tela.")

fimalgoritmo