algoritmo "Par ou Ímpar"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : DATA_ATUAL/MES_ATUAL/ANO_ATUAL
var

    numero: Inteiro

inicio

    escreva("Digite um número: ")
    leia(numero)

    Se ((numero % 2) = 0) entao
        escreval("Par")
    senao  
        escreval("Impar")
    FimSe

fimalgoritmo