algoritmo "Contador até 10"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : DATA_ATUAL/MES_ATUAL/ANO_ATUAL
var

    Cont: Inteiro

inicio

    Cont <- 1
    Repita
        escreval(Cont)
        Cont <- Cont + 1
    Ate (Cont > 10)

fimalgoritmo