algoritmo "Somador PARA"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : DATA_ATUAL/MES_ATUAL/ANO_ATUAL
var

    N, C, S: Inteiro

inicio
    C <- 1
    Para C <- 1 ate 5 faca
        escreva("Digite um valor: ")
        leia(N)
        S <- S + N
    FimPara
    escreval("A soma dos valores é ", S)

fimalgoritmo