algoritmo "primeiro"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Gustavo Guanavara]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 2025D/06/23
var
// identificador: tipo >> bla: brinquedo

// Regras dos identificadores
// 1. deve começar com letra
// 2. os próximos caracteres posem ser letras ou números
// 3. Únicos símbolos _
// 4. Não pode ter espaço em branco
// 5. Não pode ter caracteres acentuados
// 6. Não pode ser uma palavra reservada

// Tipos:
// Inteiro      1, 3, -5
// Real         0.5, 5.0
// Caractere    "Gustavo"
// Logico       verdadeiro, falso

    msg: caractere

inicio
// escreva      >> Esreve
// escraval     >> Escreve e salta uma linh

    escreva("Olá, Mundo!")
    escreval("Me livrei da maldição!")

    escreval("Escrever e saltar a linha")

    escreval("")
    msg <- "Olá, Mundo! 🌎"
    escreval("O conteúdo da variável `msg` é: ", msg)

fimalgoritmo