algoritmo "Nome do Programa"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : DATA_ATUAL/MES_ATUAL/ANO_ATUAL
var

    C: Inteiro

inicio

    // Conta de 1 a 10
    Para C <- 1 ate 10 faca
        escreval(C)
    FimPara

    escreval("\n=====\n")

    // Conta de 1 a 10, de 2 em dois
    Para C <- 1 ate 10 passo 2 faca
        escreval(C)
    FimPara

    escreval("\n=====\n")

    // Conta de 10 a 1
    Para C <- 10 ate 1 passo -1 faca
        escreval(C)
    FimPara

fimalgoritmo